import Web3 from 'web3';
const web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));
// const web3 = new Web3(new Web3.providers.HttpProvider("http://rinkeby.infura.io"));

var pollsterABI = [{"constant":true,"inputs":[],"name":"getBalance","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"pollNum","type":"uint256"}],"name":"getReward","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[],"name":"withdraw","outputs":[{"name":"transferedAmount","type":"uint256"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"pollNum","type":"uint256"}],"name":"getnumVoters","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"pollNumber","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"pollNum","type":"uint256"}],"name":"getResults","outputs":[{"name":"","type":"string"},{"name":"","type":"uint256[]"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_question","type":"string"},{"name":"_choices","type":"uint256[]"},{"name":"_numPolls","type":"uint256"}],"name":"newPoll","outputs":[{"name":"newPollNumber","type":"uint256"}],"payable":true,"type":"function"},{"constant":false,"inputs":[{"name":"pollNum","type":"uint256"},{"name":"_choice","type":"uint256"}],"name":"vote","outputs":[{"name":"","type":"bool"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"pollNum","type":"uint256"}],"name":"getQuestion","outputs":[{"name":"","type":"string"},{"name":"","type":"uint256[]"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"getNumPolls","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"inputs":[],"payable":false,"type":"constructor"},{"payable":false,"type":"fallback"},{"anonymous":false,"inputs":[{"indexed":false,"name":"","type":"address"}],"name":"VoteSubmitted","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"","type":"address"},{"indexed":false,"name":"","type":"string"}],"name":"PollOpened","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"","type":"address"},{"indexed":false,"name":"","type":"string"},{"indexed":false,"name":"","type":"uint256[]"},{"indexed":false,"name":"","type":"uint256[]"}],"name":"PollClosed","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"","type":"address"},{"indexed":false,"name":"","type":"string"}],"name":"PollReset","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"","type":"address"}],"name":"Withdrawal","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"","type":"uint256"}],"name":"RewardSet","type":"event"}];

var pollsterAddress = '0x88db687635f101a8eb5d3876fb640a0f0f69a0ef'; // 0x26d49ac6aac07ca8199eaa196946e6550d3a320b

const pollsterContract = web3.eth.contract(pollsterABI).at(pollsterAddress);

var account = web3.eth.accounts[1];
var balance = web3.fromWei(web3.eth.getBalance(account).toString());

export{pollsterContract, account, balance, web3};
